In [1]:
import numpy as np

In [2]:
input=100
output =20
state=0

In [3]:
timesteps=100

In [4]:
state=np.zeros((output,))

In [5]:
w=np.random.random((output,input))

In [6]:
u=np.random.random((output,output))

In [7]:
b=np.random.random((output,))

In [8]:
inputs=np.random.random((timesteps,input))

In [9]:
outputs=[]
for i in inputs:
    out=np.tanh(np.dot(w,i)+np.dot(u,state)+b)
    state=out
    outputs.append(out)
final=np.concatenate(outputs,axis=0)
final_out=final.reshape(timesteps,output)
    

In [10]:
final_out

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [11]:
w

array([[0.18712113, 0.64645037, 0.86191111, ..., 0.37262633, 0.35748966,
        0.19153342],
       [0.82565209, 0.61761794, 0.82411593, ..., 0.8881299 , 0.3247865 ,
        0.2301568 ],
       [0.6032191 , 0.374126  , 0.70430685, ..., 0.97672955, 0.82441015,
        0.19048186],
       ...,
       [0.31417485, 0.05512949, 0.25192655, ..., 0.52595469, 0.61226754,
        0.24431762],
       [0.20415342, 0.53149887, 0.2063662 , ..., 0.04141511, 0.82033412,
        0.28784758],
       [0.86454529, 0.7818259 , 0.82353605, ..., 0.31978369, 0.92122082,
        0.06432232]])

In [12]:
final.shape

(2000,)

In [13]:
outputs

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.]),
 array([1., 1., 1., 